[workspace]
resolver = "2"
members = ["crates/primitives"]
exclude = ["examples"]

[workspace.package]
authors = ["Upbolt"]
edition = "2021"
license = "MIT"
repository = "https://github.com/leptix/leptix"
version = "0.2.1"
